#!/usr/bin/env bash

ELASTICSEARCH_SERVICE_HOST=${ELASTICSEARCH_SERVICE_HOST:-"localhost"}
ELASTICSEARCH_SERVICE_PORT=${ELASTICSEARCH_SERVICE_PORT:-"9200"}

ELASTICSEARCH_API_ENDPOINT="http://$ELASTICSEARCH_SERVICE_HOST:$ELASTICSEARCH_SERVICE_PORT"

ELASTICSEARCH_SNAPSHOT_TYPE=${ELASTICSEARCH_SNAPSHOT_TYPE:-"fs"}

ELASTICSEARCH_SNAPSHOT_REPOSITORY=${ELASTICSEARCH_SNAPSHOT_REPOSITORY:-"backups"}

ELASTICSEARCH_SNAPSHOT_FS_LOCATION=${ELASTICSEARCH_SNAPSHOT_FS_LOCATION:-"/var/lib/es/snapshots/$ELASTICSEARCH_SNAPSHOT_REPOSITORY"}

ELASTICSEARCH_SNAPSHOT_S3_BUCKET=${ELASTICSEARCH_SNAPSHOT_S3_BUCKET:-"es-snapshots-$ELASTICSEARCH_SNAPSHOT_REPOSITORY"}

if [[ "$ELASTICSEARCH_SNAPSHOT_TYPE" = "fs" ]]; then
  read -r -d '' settings <<-EOM
  {
    "location": "$ELASTICSEARCH_SNAPSHOT_FS_LOCATION"
  }
EOM
elif [[ "$ELASTICSEARCH_SNAPSHOT_TYPE" = "s3" ]]; then
  read -r -d '' settings <<-EOM
  {
    "bucket": "$ELASTICSEARCH_SNAPSHOT_S3_BUCKET"
  }
EOM
else
  echo "ELASTICSEARCH_SNAPSHOT_TYPE should be one of: 'fs', 's3'"
  exit 1
fi

read -r -d '' request <<-EOM
{
  "type": "$ELASTICSEARCH_SNAPSHOT_TYPE",
  "settings": $settings
}
EOM

curl \
  -X PUT \
  $ELASTICSEARCH_API_ENDPOINT/_snapshot/$ELASTICSEARCH_SNAPSHOT_REPOSITORY \
  -d "$request"

curl \
  -X POST \
  $ELASTICSEARCH_API_ENDPOINT/_snapshot/$ELASTICSEARCH_SNAPSHOT_REPOSITORY/snapshot_$(date +%Y%m%d-%H%M%S-%s)\?wait_for_completion\=true
